#!/bin/bash
# configure eth1
echo "configure eth1 inet static"
echo "iface eth1 inet static" >> /etc/network/interfaces
echo "Enter ip-address : "
read ip
if [ -L ip ] ; then
  echo "$ip"
echo "address $ip" >> /etc/network/interfaces  
fi
echo "Enter netmask : "
read mask
if [ -L mask ] ; then
  echo "$mask"
fi
echo "netmask $mask" >> /etc/network/interfaces
echo "auto eth1" >> /etc/network/interfaces
